services:
  service:
    environment:
      - IGNORE_DOS_ATTRIBUTES=true
      - VOLUME_SIZE_LIMIT=1.7T
    # https://github.com/containers/podman/issues/20418
    # https://github.com/containers/podman/pull/20962
    # restart: unless-stopped
    restart: always
    ports:
      - "445:445"
    volumes:
      - /Toshiba-20200821002664F:/opt
    image: mbentley/timemachine:smb-20240821  # https://github.com/mbentley/docker-timemachine/commit/e58fe89f645fe19d7aa96cff0bf2e77398bc95e5
