version: "3.7"
services:
  timemachine:
    environment:
      - TM_USERNAME=alexis
      - TM_GROUPNAME=alexis
      - PASSWORD=${PASS}
      - SHARE_NAME=Alexis Time Machine
      - DEBUG_LEVEL=3
    restart: unless-stopped
    ports:
      - 445:445
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/${UUID}:/opt/alexis:rw
    container_name: timemachine
    image: mbentley/timemachine:smb
    ulimits:
      nofile:
        hard: 65535 # 2^16-1, max uint16_t value
        soft: 65535 # 2^16-1, max uint16_t value
