services:
  service:
    environment:
      - IGNORE_DOS_ATTRIBUTES=true
    restart: unless-stopped
    ports:
      - "445:445"
    volumes:
      - /mnt/timemachine/backup:/opt:rw
    image: mbentley/timemachine:smb-20231220  # https://github.com/mbentley/docker-timemachine/commit/a3b67f45e28d54b8c73d150261b05f07d3cffd63
