services:
  timemachine:
    environment:
      - IGNORE_DOS_ATTRIBUTES=true
      - VOLUME_SIZE_LIMIT=1.7T
    # https://github.com/containers/podman/issues/20418
    # https://github.com/containers/podman/pull/20962
    # restart: unless-stopped
    restart: always
    ports:
      - "445:445"
    volumes:
      - /TimeMachine/timemachine:/opt
    image: mbentley/timemachine:smb-20240821  # https://github.com/mbentley/docker-timemachine/commit/e58fe89f645fe19d7aa96cff0bf2e77398bc95e5
  samba:
    image: ghcr.io/servercontainers/samba:smbd-only-a3.21.2-s4.20.6-r1
    environment:
      ACCOUNT_user: "user:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:A6932FF339E3E295D2E807CB0F03D52B:[U          ]:LCT-678823B4:"
      SAMBA_VOLUME_CONFIG_timemachine: "[TimeMachineOld]; path=/shares/timemachine_old; valid users = user; guest ok = no; read only = yes; browseable = yes"
      SAMBA_VOLUME_CONFIG_media: "[Media]; path=/shares/media; valid user = user; guest ok = no; read only = yes; browseable = yes"
      FAIL_FAST: 1
      WSDD2_DISABLE: 1
      AVAHI_DISABLE: 1
      NETBIOS_DISABLE: 1
    ports:
      - "446:445"
    volumes:
      - /TimeMachine/timemachine_old:/shares/timemachine_old
      - /TimeMachine/media:/shares/media
    # https://github.com/containers/podman/issues/20418
    # https://github.com/containers/podman/pull/20962
    # restart: unless-stopped
    restart: always
