#cloud-config
prefer_fqdn_over_hostname: false
hostname: TimeMachine
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII76gjWeMy9xfu7EAD2guCp4QoP9UGQtPEbQgsFLjXSE
locale: de_DE.UTF-8
timezone: Europe/Berlin
runcmd:
  - set -e
  - setenforce Permissive && getenforce
  - sed -i 's/^SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
  - DEFAULT_USERNAME=$(basename /home/*)
  - mkdir /home/"$DEFAULT_USERNAME"/.bashrc.d
  - echo "alias podman='sudo podman'" >> /home/"$DEFAULT_USERNAME"/.bashrc.d/aliases
  - echo "alias pc='sudo podman compose'" >> /home/"$DEFAULT_USERNAME"/.bashrc.d/aliases
  - chown -R 1000:1000 /home/"$DEFAULT_USERNAME"/.bashrc.d
  - systemctl enable podman.socket
  - systemctl start podman.socket
  - systemctl enable podman-restart
  - systemctl start podman-restart
  - "COMPOSE_PATH=/usr/bin/docker-compose && curl --location 'https://github.com/docker/compose/releases/download/v2.32.1/docker-compose-linux-x86_64' --output $COMPOSE_PATH && chmod 755 $COMPOSE_PATH"
  - dnf install -y https://zfsonlinux.org/epel/zfs-release-2-3$(rpm --eval "%{dist}").noarch.rpm
  - dnf config-manager --disable zfs
  - dnf config-manager --enable zfs-kmod
  - dnf install -y zfs
  - /sbin/modprobe zfs
  - zpool import Toshiba-20200821002664F
  - cd /home/"$DEFAULT_USERNAME"
  - git clone 'https://github.com/Alex1s/timemachine.git'
  - chown -R 1000:1000 timemachine
  - cd timemachine && podman compose up -d && cd -
  - reboot now
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - podman
  - git-core
  - langpacks-en
  - langpacks-de
